import jsonloader from './source/jsonloader.js';
import bodyclass from './source/bodyclass.js';
import breadcrumb from './source/breadcrumb.js';
import formvalidator from './source/formvalidator.js';
import fullscreen from './source/fullscreen.js';
import gridVisualizer from './source/grid-visualizer.js';
import owlCarousel from './source/owlCarousel.js';
import prices from './source/prices.js';
import spamspan from './source/spamspan.js';
import lazyload from './source/lazyload.js';

jsonloader();
bodyclass();
breadcrumb();
formvalidator();
fullscreen();
gridVisualizer();
prices();
spamspan();
owlCarousel();
lazyload();